[workspace]
resolver = "2"

members = ["llvm2yul", "yuler", "yullc"]
exclude = ["examples"]

[workspace.dependencies]
yuler = { version = "0.1", path = "./yuler" }
llvm2yul = { version = "0.1", path = "./llvm2yul" }

anyhow = "1.0.81"
