[package]
name = "yullc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
llvm2yul.workspace = true
yuler.workspace = true

clap = { version = "4.5.4", features = ["derive"] }
